---
title: "Read Me"

---



## R Markdown

READ ME:
This repository contains the R script, result output, codebook, and readme for the final project of Getting & Cleaning Data course needed to complete the assignment during Week 4.

The purpose of this project is to demonstrate the ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. A full description of the data used in this project can be found at 'The UCI Machine Learning Repository'(http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

CodeBook.md describes the how to use all this, variables, the data, and any transformations or work that was performed to clean up the data.

run_analysis.R contains all the code to perform the analyses described in the 5 steps. They can be launched in RStudio by just importing the file.

The output of the 5th step is called ResultTidyData.txt, and uploaded in the course project's form.



